# Describes the format for available fan services
set_fan_speed:
  name: Speed control
  description: Set the fan speed.
  fields:
    speed:
      name: Speed
      description: Fan speed.
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: %
          mode: slider

set_mode:
  name: Always on control
  description: Enable or disable the Always on mode.
  fields:
    always_on:
      name: Always ON
      description: true to enable Always on mode, false to set the default behavior
      example: true
      default: true
      selector:
        boolean:
